# Generated by Django 4.0.4 on 2022-04-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Passenger', '0002_alter_passengers_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengers',
            name='country',
            field=models.CharField(default='country', max_length=20),
        ),
        migrations.AddField(
            model_name='passengers',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='passengers',
            name='age',
            field=models.SmallIntegerField(default='18'),
        ),
        migrations.AlterField(
            model_name='passengers',
            name='email',
            field=models.CharField(max_length=40),
        ),
    ]
